[build]
  publish = "/"

[dev]
  framework = "#static"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com; style-src 'self' https://cdn.jsdelivr.net 'unsafe-inline'; img-src 'self' data:; font-src 'self' https://cdn.jsdelivr.net; connect-src 'self'"
    
[[headers]]
  for = "/files/*"
  [headers.values]
    Content-Type = "application/octet-stream"
    Content-Disposition = "attachment"
    Access-Control-Allow-Origin = "*"
    
[[headers]]
  for = "/files/CV_JesusGarciaMolina.pdf"
  [headers.values]
    Content-Type = "application/pdf"
    Content-Disposition = "attachment; filename=CV_JesusGarciaMolina.pdf"
